### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by Memurame** [bweben/lag-billard#1]
Die app.py kann ich ohne Probleme ausführen.
Bei der billard.py habe ich so meine Probleme mit dem import von tkinter.tix.
Bis jetzt habe ich es noch nicht zu laufen gebracht.

Aber ich denke mit einer requirements.txt würde es keine Probleme mit nicht vorhandenen Modulen geben.

Grüessli Tom

**Comment by bweben** [comment]
Ist ein Schulprojekt aber ein requirements.txt oder environment.yaml (für conda) wäre sicher in Zukunft sinnvoll.

Gruss
